### ISSUE TITLE
Hanging workflow with dbt-snowflake on dbt-core1.0.1 & SQLFluff==0.9.4

### ISSUE THREAD

**Issue by amf-32** [sqlfluff/sqlfluff-github-actions#19]
I've recently switched to dbt-core 1.0.1 (within dbt-snowflake1.0.0) - my previous linting workflow ran without issue, using a dummy profiles.yml (to avoid github secrets and actual database connections) and standard config:

```
#config

[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt

[sqlfluff:templater:dbt]
load_macros_from_path = macros
```
However after updating dbt_project.yml and generally switching to 1.0.1 - this workflow now hangs. The only actual workflow change made is to install `dbt-snowflake`
```
#simplified workflow 
name: Lint Models

on: [push]
# Dummy profiles.yml location
env:
  DBT_PROFILES_DIR: .github/

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.9.6"
      - name: Install SQLFluff and dbt
        run: "pip install sqlfluff-templater-dbt==0.9.4 dbt-snowflake"
      - name: dbt deps
        run: "dbt deps"
      - name: Lint models
        run: "sqlfluff lint models"
```

This results in a completely hanging linting step on the workflow. 
I have been able to run `sqlfluff lint models/*` locally without issue, whilst on dbt-core1.0.1 and sqlfluff 0.9.4. It also seems as though the dbt step of sqlfluff is still running properly from what I've seen in the workflow output.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/59886834/153441517-ceb4fd15-7517-4366-9116-1cf081aacd32.png">

Any help would be appreciated, although it seems as though all of the examples here are on versions <1.0.0.
