### ISSUE TITLE
How to use --formatter dbt on Drizly？

### ISSUE THREAD

**Issue by chinahamu** [sqlfluff/sqlfluff-github-actions#22]
I Can See this error
`
  no dbt_project.yml found at expected path /home/runner/work/project/project/dbt_project.yml
`

I set an environment variable to solve this problem.

```
jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
    env:
      DBT_PROFILES_DIR: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/dbt/
```

 But the result remained the same.
